# For more information about the configurations used
# in this file, please see the Travis CI documentation:
# https://docs.travis-ci.com/

after_failure:
  - sudo cat /var/log/apache2/error.log
  - sudo cat /var/log/apache2/access.log

cache:
  directories: node_modules

env:
  global:
    - secure: "itatOgspOE49LX1fczgut51/3AGiCE7ueMeUHdGseB7cWfyFlJ2eUozspXBfbmWtEls8Y97/V1Q8vZty/WXJ2Q3CdxjK8TBBhVycRgK5Qp03eG/yFy/G5hXN1mGil4KwIwqHVYAQvCVcuDv0Ek4V+PEfNp8KGkRILxP2a6kRjgw="

jobs:
  include:

    - stage: test

      before_script: ./bin/setup/setup.sh
      dist: precise
      env:
        - APACHE_VERSION="2.2"
        - CONF_TARGET="default"

    - stage: test
      before_script: ./bin/setup/setup.sh
      env:
       - APACHE_VERSION="2.4"
       - CONF_TARGET="000-default.conf"

    - stage: "update dist/ directory"
      script: .travis/update-dist.sh

language: node_js

node_js: node

sudo: required
